// lib/data.ts
// Mock catalog for AeroPulse Bike Studio. Prices/stock are illustrative demo data.
import { Bike, LifestyleImage } from "./types";

const STYLE_SUFFIX =
  "studio product photography, dark graphite void background with a single amber rim-light, " +
  "carbon-fibre texture visible, low camera angle, cinematic, ultra-detailed, 85mm lens, no text, no watermark";

export const BIKES: Bike[] = [
  {
    id: "vantage-slr",
    name: "Vantage SLR",
    series: "Aero Line",
    category: "aero-road",
    tagline: "Built to out-run the wind, not just the clock.",
    priceTHB: 389000,
    weightKg: 6.9,
    aeroRating: 97,
    comfortRating: 58,
    groupset: "Shimano Dura-Ace Di2 12-speed",
    frame: "Full monocoque T1100 carbon, truncated-aerofoil tube profile",
    terrainFit: ["road", "track"],
    distanceFit: ["mid", "long"],
    feelFit: ["aero"],
    experienceFit: ["regular", "racer"],
    specialTags: ["aero-max", "lightest"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: false, etaDays: 21 },
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: false, etaDays: 14 },
      { size: "XL", heightRangeCm: [188, 198], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `Matte black and gunmetal aero road bicycle "Vantage SLR", deep-section carbon wheels, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of integrated cockpit and aero handlebar on a black carbon road bike, ${STYLE_SUFFIX}`,
      `Close-up of deep-section carbon wheel and disc brake rotor, amber accent light, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "Dura-Ace Di2 12-speed, 52/36" },
      { label: "Wheels", value: "62mm carbon tubeless, ceramic bearings" },
      { label: "Drag coefficient", value: "CdA 0.187 (wind-tunnel verified)" },
      { label: "Stack / Reach (M)", value: "540 / 388 mm" },
    ],
  },
  {
    id: "meridian-comfort",
    name: "Meridian Comfort+",
    series: "Endurance Line",
    category: "endurance-road",
    tagline: "The century-ride bike that forgets it's carbon.",
    priceTHB: 178000,
    weightKg: 8.4,
    aeroRating: 61,
    comfortRating: 92,
    groupset: "Shimano Ultegra Di2 12-speed",
    frame: "Endurance-geometry carbon, IsoFlex seat mast",
    terrainFit: ["road", "gravel"],
    distanceFit: ["long", "century"],
    feelFit: ["endurance", "versatile"],
    experienceFit: ["beginner", "regular"],
    specialTags: ["none"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: true, etaDays: null },
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
      { size: "XL", heightRangeCm: [188, 198], inStock: false, etaDays: 10 },
    ],
    heroImagePrompt: `Bone-white and graphite endurance road bicycle "Meridian Comfort+", relaxed geometry, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of IsoFlex seat mast and saddle on a white carbon endurance bike, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "Ultegra Di2 12-speed, 50/34" },
      { label: "Tyre clearance", value: "Up to 35mm, tubeless-ready" },
      { label: "Vibration damping", value: "IsoFlex mast, -28% road buzz vs. race frame" },
      { label: "Stack / Reach (M)", value: "565 / 380 mm" },
    ],
  },
  {
    id: "driftpath-gx",
    name: "Driftpath GX",
    series: "Gravel Line",
    category: "gravel",
    tagline: "One bike, every surface you can find.",
    priceTHB: 149000,
    weightKg: 9.1,
    aeroRating: 48,
    comfortRating: 85,
    groupset: "SRAM Rival XPLR AXS 1x12",
    frame: "Double-butted carbon, mud/rack mounts",
    terrainFit: ["gravel", "road", "city"],
    distanceFit: ["mid", "long"],
    feelFit: ["versatile", "endurance"],
    experienceFit: ["beginner", "regular"],
    specialTags: ["none"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: true, etaDays: null },
      { size: "S", heightRangeCm: [162, 172], inStock: false, etaDays: 7 },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
      { size: "XL", heightRangeCm: [188, 198], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `Clay-orange and graphite gravel bicycle "Driftpath GX" with wide knobby tyres, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of gravel bike wide tyre and 1x AXS rear derailleur, dust and dirt texture, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "Rival XPLR AXS 1x12, 40T" },
      { label: "Tyre clearance", value: "Up to 45mm" },
      { label: "Mounts", value: "3x cargo, rear rack, fender-ready" },
      { label: "Stack / Reach (M)", value: "580 / 385 mm" },
    ],
  },
  {
    id: "vantage-slr-disc",
    name: "Vantage SLR Disc Team",
    series: "Aero Line",
    category: "aero-road",
    tagline: "The team-issue frame, without the team contract.",
    priceTHB: 449000,
    weightKg: 6.7,
    aeroRating: 99,
    comfortRating: 55,
    groupset: "SRAM Red AXS 12-speed",
    frame: "Full monocoque T1100 carbon, hookless aero rims",
    terrainFit: ["road", "track"],
    distanceFit: ["mid", "long"],
    feelFit: ["aero"],
    experienceFit: ["racer"],
    specialTags: ["aero-max"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: false, etaDays: 30 },
      { size: "S", heightRangeCm: [162, 172], inStock: false, etaDays: 30 },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
      { size: "XL", heightRangeCm: [188, 198], inStock: false, etaDays: 21 },
    ],
    heroImagePrompt: `Race-team livery aero road bicycle "Vantage SLR Disc Team" in graphite and amber, podium lighting, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of SRAM Red AXS shifter and hydraulic disc caliper, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "SRAM Red AXS, 12-speed" },
      { label: "Wheels", value: "64mm hookless carbon, tubeless" },
      { label: "Drag coefficient", value: "CdA 0.181 (wind-tunnel verified)" },
      { label: "Stack / Reach (M)", value: "533 / 390 mm" },
    ],
  },
  {
    id: "solstice-tt",
    name: "Solstice TT",
    series: "Time Trial Line",
    category: "time-trial",
    tagline: "Every second against the clock, engineered away.",
    priceTHB: 329000,
    weightKg: 8.9,
    aeroRating: 95,
    comfortRating: 40,
    groupset: "Shimano Dura-Ace Di2 12-speed, TT shifters",
    frame: "Full monocoque carbon, Kammtail aero tubes",
    terrainFit: ["track", "road"],
    distanceFit: ["short", "mid"],
    feelFit: ["aero"],
    experienceFit: ["racer"],
    specialTags: ["aero-max"],
    sizes: [
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: false, etaDays: 25 },
    ],
    heroImagePrompt: `Triathlon time-trial bicycle "Solstice TT" with aero base bar, dark void background, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of triathlon aerobar extensions and hydration mount, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "Dura-Ace Di2, bar-end TT shifters" },
      { label: "Cockpit", value: "Fully integrated aero base bar + extensions" },
      { label: "Drag coefficient", value: "CdA 0.176 (wind-tunnel verified)" },
      { label: "Stack / Reach (M)", value: "505 / 400 mm" },
    ],
  },
  {
    id: "citypulse-e",
    name: "CityPulse E-Perform",
    series: "Electric Line",
    category: "electric-performance",
    tagline: "Effort is optional. Speed is not.",
    priceTHB: 259000,
    weightKg: 11.8,
    aeroRating: 66,
    comfortRating: 80,
    groupset: "Shimano 105 Di2 12-speed + FAZUA 60Nm mid-drive",
    frame: "Carbon, integrated battery, removable range extender",
    terrainFit: ["city", "road"],
    distanceFit: ["mid", "long"],
    feelFit: ["assisted", "versatile"],
    experienceFit: ["beginner", "regular"],
    specialTags: ["e-assist"],
    sizes: [
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `Sleek electric-assist road bicycle "CityPulse E-Perform" with hidden battery, graphite and amber trim, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of integrated top-tube display and hidden e-bike battery hatch, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Motor", value: "FAZUA Ride 60, 60Nm, 250W" },
      { label: "Range", value: "80–120 km per charge" },
      { label: "Battery", value: "430Wh integrated, removable" },
      { label: "Stack / Reach (M)", value: "555 / 382 mm" },
    ],
  },
  {
    id: "novaline-urban",
    name: "Novaline Urban",
    series: "Urban Line",
    category: "urban-performance",
    tagline: "A commute that out-accelerates the taxi.",
    priceTHB: 96000,
    weightKg: 9.6,
    aeroRating: 55,
    comfortRating: 75,
    groupset: "Shimano GRX 11-speed, flat-bar",
    frame: "Aluminum, internal cable routing, rack mounts",
    terrainFit: ["city", "gravel"],
    distanceFit: ["short", "mid"],
    feelFit: ["versatile"],
    experienceFit: ["beginner", "regular"],
    specialTags: ["none"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: true, etaDays: null },
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `Matte graphite urban flat-bar bicycle "Novaline Urban" with rack mounts, city studio backdrop, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of flat handlebar and city commuter grips, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Drivetrain", value: "GRX 11-speed, 40T" },
      { label: "Mounts", value: "Rear rack, fenders, front basket" },
      { label: "Tyres", value: "32mm puncture-resistant" },
      { label: "Stack / Reach (M)", value: "590 / 375 mm" },
    ],
  },
  {
    id: "featherline-ul",
    name: "Featherline UL",
    series: "Ultralight Line",
    category: "endurance-road",
    tagline: "Every gram argued with and removed.",
    priceTHB: 299000,
    weightKg: 5.9,
    aeroRating: 70,
    comfortRating: 78,
    groupset: "SRAM Red AXS 12-speed",
    frame: "Ultralight T1000 carbon, 690g frame weight",
    terrainFit: ["road"],
    distanceFit: ["mid", "long"],
    feelFit: ["endurance", "versatile"],
    experienceFit: ["regular", "racer"],
    specialTags: ["lightest"],
    sizes: [
      { size: "XS", heightRangeCm: [150, 162], inStock: true, etaDays: null },
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: false, etaDays: 18 },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `Ultra-light raw-carbon road bicycle "Featherline UL" on a scale, minimalist void backdrop, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of raw unpainted carbon frame joint showing weave, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Frame weight", value: "690g (56cm, unpainted)" },
      { label: "Complete build", value: "5.9kg (size M)" },
      { label: "Drivetrain", value: "SRAM Red AXS, 12-speed" },
      { label: "Stack / Reach (M)", value: "550 / 385 mm" },
    ],
  },
  {
    id: "packline-fold",
    name: "Packline Fold Aero",
    series: "Travel Line",
    category: "urban-performance",
    tagline: "Fits in the overhead bin. Rides like it doesn't.",
    priceTHB: 138000,
    weightKg: 10.4,
    aeroRating: 58,
    comfortRating: 70,
    groupset: "Shimano 105 Di2 11-speed",
    frame: "Folding carbon/alloy hybrid, magnetic hinge lock",
    terrainFit: ["city", "road"],
    distanceFit: ["short", "mid"],
    feelFit: ["versatile"],
    experienceFit: ["beginner", "regular"],
    specialTags: ["packable"],
    sizes: [
      { size: "S", heightRangeCm: [162, 172], inStock: true, etaDays: null },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: false, etaDays: 12 },
    ],
    heroImagePrompt: `Compact folding performance bicycle "Packline Fold Aero" mid-fold, travel case beside it, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of magnetic folding hinge mechanism on a carbon bicycle frame, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Folded size", value: "78 × 65 × 32 cm" },
      { label: "Fold time", value: "14 seconds" },
      { label: "Drivetrain", value: "105 Di2, 11-speed" },
      { label: "Stack / Reach (M)", value: "560 / 378 mm" },
    ],
  },
  {
    id: "vantage-slr-e",
    name: "Vantage SLR-E",
    series: "Electric Line",
    category: "electric-performance",
    tagline: "Aero speed, with a second engine you don't see.",
    priceTHB: 419000,
    weightKg: 9.8,
    aeroRating: 90,
    comfortRating: 62,
    groupset: "Shimano Dura-Ace Di2 12-speed + FAZUA 60Nm mid-drive",
    frame: "Full monocoque T1100 carbon, aero tube profile, hidden battery",
    terrainFit: ["road", "track"],
    distanceFit: ["mid", "long", "century"],
    feelFit: ["aero", "assisted"],
    experienceFit: ["regular", "racer"],
    specialTags: ["aero-max", "e-assist"],
    sizes: [
      { size: "S", heightRangeCm: [162, 172], inStock: false, etaDays: 28 },
      { size: "M", heightRangeCm: [172, 180], inStock: true, etaDays: null },
      { size: "L", heightRangeCm: [180, 188], inStock: true, etaDays: null },
    ],
    heroImagePrompt: `High-performance electric aero road bicycle "Vantage SLR-E" with fully hidden motor and battery, ${STYLE_SUFFIX}`,
    detailImagePrompts: [
      `Close-up of aero road bike bottom bracket with hidden e-assist motor, ${STYLE_SUFFIX}`,
    ],
    specSheet: [
      { label: "Motor", value: "FAZUA Ride 60, 60Nm, 250W, fully hidden" },
      { label: "Drag coefficient", value: "CdA 0.190 (wind-tunnel verified)" },
      { label: "Range", value: "70–100 km per charge" },
      { label: "Stack / Reach (M)", value: "545 / 388 mm" },
    ],
  },
];

export const LIFESTYLE_IMAGES: LifestyleImage[] = [
  {
    id: "life-01",
    caption: "Dawn ride, Bangkok's empty expressway ramps",
    prompt: `Cyclist on a matte black aero road bike riding an empty elevated expressway at dawn, low golden light through haze, amber and graphite tones, cinematic wide shot, no visible face, no text, no logos`,
  },
  {
    id: "life-02",
    caption: "Studio fit session with a AeroPulse specialist",
    prompt: `Bike fitting studio, technician adjusting saddle height on a premium road bike using a laser measurement tool, dark graphite studio, amber accent lighting, editorial photography, no text, no logos`,
  },
  {
    id: "life-03",
    caption: "Gravel line, first light on a forest trail",
    prompt: `Gravel bicycle leaning against a tree at the edge of a misty forest trail at sunrise, shallow depth of field, warm clay-orange rim light, editorial travel photography, no people, no text`,
  },
  {
    id: "life-04",
    caption: "Wind-tunnel validation session",
    prompt: `Aero road bicycle mounted in a wind tunnel test rig, smoke trail visualisation flowing over the frame, dark laboratory setting with blue-white measurement lights, technical photography, no text, no logos`,
  },
  {
    id: "life-05",
    caption: "Night criterium, city circuit",
    prompt: `Cyclist racing an aero road bike through a city street circuit at night under amber street lighting, motion blur on background buildings, dynamic low angle, cinematic, no visible face, no text`,
  },
];

export const BRAND = {
  name: "AeroPulse Bike Studio",
  domain: "aeropulse.puchup.com",
  tagline: "Engineered for the Second Before You Feel the Wind.",
  taglineTh: "วิศวกรรมที่ทำงานก่อนคุณจะรู้สึกถึงแรงลม",
  positioning:
    "สตูดิโอจักรยานสมรรถนะสูงระดับ SSS-Tier ที่จับคู่คุณกับจักรยานที่เหมาะกับวิธีปั่น เป้าหมาย และงบประมาณจริง ผ่านระบบ Smart Finder และทีมผู้เชี่ยวชาญ",
};
